query2:
  outputs:
    dev:
      dataset: dbt_sample_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: cloudside-academy
      threads: 5
      type: bigquery
  target: dev
query3:
  outputs:
    dev:
      dataset: dbt_sample_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: cloudside-academy
      threads: 5
      type: bigquery
  target: dev
sample:
  outputs:
    dev:
      dataset: dbt_sample_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: cloudside-academy
      threads: 4
      type: bigquery
  target: dev
